version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
